### ISSUE TITLE
Disconnect Event not being shown

### ISSUE THREAD

**Issue by gkapellmann** [LiveOrDevTrying/Tcp.NET#6]
Hi,

I got a server running, and works nice, when i connect two separate clients the Connected event fires.
![image](https://user-images.githubusercontent.com/7535220/206916040-14b95d86-c910-404e-ba48-70e85aff225c.png)

But when I Diconnect one, or both, no Disconnect event or Errir event happens. 
Disconnect event only happens if I disconnect from the server. 

Is this expected behaviour? Or Should Disconnect or Error event fire also when any client disconnects?

**Comment by filip-martinko** [comment]
I have the same issue. I have TCP Server in C++.
TcpNETClient is not notified if the Server disconnects this client. The client will find out it lost the connection to the server after it tries to send some data to the server. But I would like to be informed as soon as possible because the Client sends data to the server rarely...

**Comment by LiveOrDevTrying** [comment]
Hello,

I've implemented a new feature that sends a byte[] {3} (or whatever byte array specified) from client to server and server to client to fire disconnect events when the server or client performs a graceful Disconnect(). The code has been commit and packages pushed to nuget.

Give it a try and let me know if you have any problems, thoughts, or additional feedback. Thanks!
